#################
### AUTOSTART ###
#################
# swww
exec-once = swww-daemon &
# exec-once = matugen image ~/dotfiles/wallpaper/arch2.png --source-color-index 0 &
# quickshell
exec-once = qs &
